spring:
  application:
    name: thraex-platform-registry

server:
  port: 8761

eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
#    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
#    prefer-ip-address: true
  client:
    # 服务注册中心也会将自己作为客户端来尝试注册自己,为true(默认)时自动生效
    # false 表示不向注册中心中注册自己
    register-with-eureka: false
    # 检索服务选项,当设置为True(默认值)时,会进行服务检索,注册中心不负责检索服务。
    # false 表示自己端就是注册中心,我的职责就是维护服务实例,并不需要去检索服务
    fetch-registry: false
#    availabilityZones:
#      us-east-1: zone1,zone2
#    serviceUrl:
#      zone1: http://${spring.cloud.client.ip-address}:8761/eureka/
#      zone2: http://${spring.cloud.client.ip-address}:8762/eureka/
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  profiles: replicas

server:
  port: 8762

eureka:
  client:
    availabilityZones:
      us-east-1: zone2,zone1
