spring:
  application:
    name: thraex-platform-gateway
  cloud:
    gateway:
      default-filters:
      - StripPrefix=2
      routes:
      - id: route-thraex-framework-admin
        uri: lb://thraex-framework-admin
        predicates:
        - Path=/api/admin/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

server:
  port: 8762

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: false
#    metadataMap:
#      zone: zone1
  client:
#    availabilityZones:
#      us-east-1: zone1,zone2
#    serviceUrl:
#      zone1: http://${spring.cloud.client.ip-address}:8761/eureka/
#      zone2: http://${spring.cloud.client.ip-address}:8762/eureka/
    service-url:
      default-zone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
