spring:
  profiles:
    active: jdbc
  application:
    name: thraex-platform-config
  datasource:
    name: THRAEX-DB
#    driver-class-name: com.mysql.jdbc.Driver
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/thraex-config?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: mysql
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT attribute, value FROM properties WHERE pid IN (SELECT id FROM application WHERE name = ? AND profile = ? AND label = ?) ORDER BY attribute, value
  jpa:
    database: mysql
    show-sql: true
  thymeleaf:
      cache: false
  mvc:
    static-path-pattern: /res/static/**

server:
  port: 9000

#eureka:
#  instance:
#    instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
#    # 使用IP地址注册，默认为主机名
#    preferIpAddress: true
#  client:
#    # 禁用Eureka服务发现客户端
##    enabled: false
#    serviceUrl:
#      defaultZone: http://${CFG_EUREKA_HOST:${spring.cloud.client.ip-address}}:${CFG_EUREKA_PORT:8761}/eureka/
